The following values were not passed to `accelerate launch` and had defaults used instead:
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 5, in <module>
    from model_base import TransformerModelLoader
ModuleNotFoundError: No module named 'model_base'
Traceback (most recent call last):
  File "/home/winnieyangwn/miniconda3/envs/refat/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1194, in launch_command
    simple_launcher(args)
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/launch.py", line 780, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/winnieyangwn/miniconda3/envs/refat/bin/python3.11', 'run_truthfulqa_basics.py', '--model_path=meta-llama/Llama-3.1-8B-Instruct']' returned non-zero exit status 1.
srun: error: cr6-p548xlarge-26: task 0: Exited with exit code 1
srun: Terminating StepId=128908.0
