The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory:
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
current_directory: /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA
[W328 00:47:29.583628400 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:29.653219511 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:29.989598003 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:29.180423497 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:30.605197635 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:30.622634488 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:30.865070591 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
[W328 00:47:30.053308945 Utils.hpp:135] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function operator())
Using 8 GPUs
Process rank: 0
cfg: Config(model_path='meta-llama/Llama-3.1-8B-Instruct', model_name='Llama-3.1-8B-Instruct', save_dir='/home/winnieyangwn/Output', entity_type='song', n_positions=1, n_train=512, n_test=128, batch_size=128, max_new_tokens=100, task_name='truthful_qa', steer_type='negative_addition', source_layer=14, target_layer=14, contrastive_type=('factual', 'misconception'), steering_strength=1)
Generating train split: 0 examples [00:00, ? examples/s]Generating train split: 72 examples [00:00, 1165.26 examples/s]
[rank2]: Traceback (most recent call last):
[rank2]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank2]:     main(model_path=args.model_path, 
[rank2]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank2]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank2]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank2]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank2]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank2]:     out = func(dataset, *args, **kwargs)
[rank2]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank2]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank2]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank2]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank2]:     out = func(dataset, *args, **kwargs)
[rank2]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank2]:     _check_valid_indices_value(start + length - 1, len(self))
[rank2]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank2]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank2]: IndexError: Index 511 out of range for dataset of size 64.
Train size: 64
Test size: 8
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank0]:     main(model_path=args.model_path, 
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank0]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank0]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank0]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank0]:     out = func(dataset, *args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank0]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank0]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank0]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank0]:     out = func(dataset, *args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank0]:     _check_valid_indices_value(start + length - 1, len(self))
[rank0]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank0]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank0]: IndexError: Index 511 out of range for dataset of size 64.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank1]:     main(model_path=args.model_path, 
[rank1]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank1]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank1]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank1]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank1]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank1]:     out = func(dataset, *args, **kwargs)
[rank1]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank1]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank1]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank1]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank1]:     out = func(dataset, *args, **kwargs)
[rank1]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank1]:     _check_valid_indices_value(start + length - 1, len(self))
[rank1]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank1]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank1]: IndexError: Index 511 out of range for dataset of size 64.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank6]:     main(model_path=args.model_path, 
[rank6]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank6]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank6]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank6]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank6]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank6]:     out = func(dataset, *args, **kwargs)
[rank6]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank6]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank6]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank6]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank6]:     out = func(dataset, *args, **kwargs)
[rank6]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank6]:     _check_valid_indices_value(start + length - 1, len(self))
[rank6]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank6]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank6]: IndexError: Index 511 out of range for dataset of size 64.
[rank4]: Traceback (most recent call last):
[rank4]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank4]:     main(model_path=args.model_path, 
[rank4]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank4]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank4]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank4]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank4]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank4]:     out = func(dataset, *args, **kwargs)
[rank4]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank4]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank4]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank4]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank4]:     out = func(dataset, *args, **kwargs)
[rank4]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank4]:     _check_valid_indices_value(start + length - 1, len(self))
[rank4]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank4]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank4]: IndexError: Index 511 out of range for dataset of size 64.
[rank5]: Traceback (most recent call last):
[rank5]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank5]:     main(model_path=args.model_path, 
[rank5]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank5]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank5]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank5]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank5]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank5]:     out = func(dataset, *args, **kwargs)
[rank5]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank5]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank5]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank5]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank5]:     out = func(dataset, *args, **kwargs)
[rank5]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank5]:     _check_valid_indices_value(start + length - 1, len(self))
[rank5]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank5]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank5]: IndexError: Index 511 out of range for dataset of size 64.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank7]:     main(model_path=args.model_path, 
[rank7]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank7]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank7]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank7]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank7]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank7]:     out = func(dataset, *args, **kwargs)
[rank7]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank7]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank7]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank7]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank7]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank7]:     out = func(dataset, *args, **kwargs)
[rank7]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank7]:     _check_valid_indices_value(start + length - 1, len(self))
[rank7]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank7]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank7]: IndexError: Index 511 out of range for dataset of size 64.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 131, in <module>
[rank3]:     main(model_path=args.model_path, 
[rank3]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/deception_and_jailbreak/src/submodules/truthfulQA/run_truthfulqa_basics.py", line 108, in main
[rank3]:     dataset_train =  dataset_train.select(range(cfg.n_train)) 
[rank3]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank3]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank3]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank3]:     out = func(dataset, *args, **kwargs)
[rank3]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3920, in select
[rank3]:     return self._select_contiguous(start, length, new_fingerprint=new_fingerprint)
[rank3]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 562, in wrapper
[rank3]:     out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
[rank3]:                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/fingerprint.py", line 442, in wrapper
[rank3]:     out = func(dataset, *args, **kwargs)
[rank3]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3981, in _select_contiguous
[rank3]:     _check_valid_indices_value(start + length - 1, len(self))
[rank3]:   File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 624, in _check_valid_indices_value
[rank3]:     raise IndexError(f"Index {index} out of range for dataset of size {size}.")
[rank3]: IndexError: Index 511 out of range for dataset of size 64.
[rank0]:[W328 00:47:35.755428509 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0328 00:47:39.830000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913807 closing signal SIGTERM
W0328 00:47:39.837000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913808 closing signal SIGTERM
W0328 00:47:39.838000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913809 closing signal SIGTERM
W0328 00:47:39.838000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913810 closing signal SIGTERM
W0328 00:47:39.839000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913811 closing signal SIGTERM
W0328 00:47:39.839000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913812 closing signal SIGTERM
W0328 00:47:39.840000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 913813 closing signal SIGTERM
E0328 00:47:42.555000 913042 /opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 913806) of binary: /home/winnieyangwn/miniconda3/envs/refat/bin/python3.11
Traceback (most recent call last):
  File "/home/winnieyangwn/miniconda3/envs/refat/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1185, in launch_command
    multi_gpu_launcher(args)
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/accelerate/commands/launch.py", line 810, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/winnieyangwn/miniconda3/envs/refat/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_truthfulqa_basics.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-28_00:47:39
  host      : cr6-p548xlarge-0.genai-h100.hpcaas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 913806)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: cr6-p548xlarge-0: task 0: Exited with exit code 1
srun: Terminating StepId=128876.0
